# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kraschowetz/Documents/C++/Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kraschowetz/Documents/C++/Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kraschowetz/Documents/C++/Engine/CMakeFiles /home/kraschowetz/Documents/C++/Engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kraschowetz/Documents/C++/Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/graphics/Canvas.o: src/graphics/Canvas.cpp.o
.PHONY : src/graphics/Canvas.o

# target to build an object file
src/graphics/Canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Canvas.cpp.o
.PHONY : src/graphics/Canvas.cpp.o

src/graphics/Canvas.i: src/graphics/Canvas.cpp.i
.PHONY : src/graphics/Canvas.i

# target to preprocess a source file
src/graphics/Canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Canvas.cpp.i
.PHONY : src/graphics/Canvas.cpp.i

src/graphics/Canvas.s: src/graphics/Canvas.cpp.s
.PHONY : src/graphics/Canvas.s

# target to generate assembly for a file
src/graphics/Canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Canvas.cpp.s
.PHONY : src/graphics/Canvas.cpp.s

src/graphics/Sprite.o: src/graphics/Sprite.cpp.o
.PHONY : src/graphics/Sprite.o

# target to build an object file
src/graphics/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Sprite.cpp.o
.PHONY : src/graphics/Sprite.cpp.o

src/graphics/Sprite.i: src/graphics/Sprite.cpp.i
.PHONY : src/graphics/Sprite.i

# target to preprocess a source file
src/graphics/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Sprite.cpp.i
.PHONY : src/graphics/Sprite.cpp.i

src/graphics/Sprite.s: src/graphics/Sprite.cpp.s
.PHONY : src/graphics/Sprite.s

# target to generate assembly for a file
src/graphics/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Sprite.cpp.s
.PHONY : src/graphics/Sprite.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main/Engine.o: src/main/Engine.cpp.o
.PHONY : src/main/Engine.o

# target to build an object file
src/main/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Engine.cpp.o
.PHONY : src/main/Engine.cpp.o

src/main/Engine.i: src/main/Engine.cpp.i
.PHONY : src/main/Engine.i

# target to preprocess a source file
src/main/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Engine.cpp.i
.PHONY : src/main/Engine.cpp.i

src/main/Engine.s: src/main/Engine.cpp.s
.PHONY : src/main/Engine.s

# target to generate assembly for a file
src/main/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Engine.cpp.s
.PHONY : src/main/Engine.cpp.s

src/main/Input.o: src/main/Input.cpp.o
.PHONY : src/main/Input.o

# target to build an object file
src/main/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Input.cpp.o
.PHONY : src/main/Input.cpp.o

src/main/Input.i: src/main/Input.cpp.i
.PHONY : src/main/Input.i

# target to preprocess a source file
src/main/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Input.cpp.i
.PHONY : src/main/Input.cpp.i

src/main/Input.s: src/main/Input.cpp.s
.PHONY : src/main/Input.s

# target to generate assembly for a file
src/main/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Input.cpp.s
.PHONY : src/main/Input.cpp.s

src/main/Node.o: src/main/Node.cpp.o
.PHONY : src/main/Node.o

# target to build an object file
src/main/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Node.cpp.o
.PHONY : src/main/Node.cpp.o

src/main/Node.i: src/main/Node.cpp.i
.PHONY : src/main/Node.i

# target to preprocess a source file
src/main/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Node.cpp.i
.PHONY : src/main/Node.cpp.i

src/main/Node.s: src/main/Node.cpp.s
.PHONY : src/main/Node.s

# target to generate assembly for a file
src/main/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Node.cpp.s
.PHONY : src/main/Node.cpp.s

src/main/Scene.o: src/main/Scene.cpp.o
.PHONY : src/main/Scene.o

# target to build an object file
src/main/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Scene.cpp.o
.PHONY : src/main/Scene.cpp.o

src/main/Scene.i: src/main/Scene.cpp.i
.PHONY : src/main/Scene.i

# target to preprocess a source file
src/main/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Scene.cpp.i
.PHONY : src/main/Scene.cpp.i

src/main/Scene.s: src/main/Scene.cpp.s
.PHONY : src/main/Scene.s

# target to generate assembly for a file
src/main/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Scene.cpp.s
.PHONY : src/main/Scene.cpp.s

src/main/Timer.o: src/main/Timer.cpp.o
.PHONY : src/main/Timer.o

# target to build an object file
src/main/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Timer.cpp.o
.PHONY : src/main/Timer.cpp.o

src/main/Timer.i: src/main/Timer.cpp.i
.PHONY : src/main/Timer.i

# target to preprocess a source file
src/main/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Timer.cpp.i
.PHONY : src/main/Timer.cpp.i

src/main/Timer.s: src/main/Timer.cpp.s
.PHONY : src/main/Timer.s

# target to generate assembly for a file
src/main/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Timer.cpp.s
.PHONY : src/main/Timer.cpp.s

src/main/Vector2.o: src/main/Vector2.cpp.o
.PHONY : src/main/Vector2.o

# target to build an object file
src/main/Vector2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Vector2.cpp.o
.PHONY : src/main/Vector2.cpp.o

src/main/Vector2.i: src/main/Vector2.cpp.i
.PHONY : src/main/Vector2.i

# target to preprocess a source file
src/main/Vector2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Vector2.cpp.i
.PHONY : src/main/Vector2.cpp.i

src/main/Vector2.s: src/main/Vector2.cpp.s
.PHONY : src/main/Vector2.s

# target to generate assembly for a file
src/main/Vector2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/Vector2.cpp.s
.PHONY : src/main/Vector2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/graphics/Canvas.o"
	@echo "... src/graphics/Canvas.i"
	@echo "... src/graphics/Canvas.s"
	@echo "... src/graphics/Sprite.o"
	@echo "... src/graphics/Sprite.i"
	@echo "... src/graphics/Sprite.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main/Engine.o"
	@echo "... src/main/Engine.i"
	@echo "... src/main/Engine.s"
	@echo "... src/main/Input.o"
	@echo "... src/main/Input.i"
	@echo "... src/main/Input.s"
	@echo "... src/main/Node.o"
	@echo "... src/main/Node.i"
	@echo "... src/main/Node.s"
	@echo "... src/main/Scene.o"
	@echo "... src/main/Scene.i"
	@echo "... src/main/Scene.s"
	@echo "... src/main/Timer.o"
	@echo "... src/main/Timer.i"
	@echo "... src/main/Timer.s"
	@echo "... src/main/Vector2.o"
	@echo "... src/main/Vector2.i"
	@echo "... src/main/Vector2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

